# Generated by Django 6.0.5 on 2026-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('co2e', models.FloatField()),
                ('suspicious', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
    ]
